package Parser;

public enum Actions {
    OPENBRACKET,
    SETTYPEOPEN,
    SETTYPECLOSE,
    PARENTHESESOPEN,
    PARENTHESESCLOSE,
    IDENTIFIER,
    NUMBERVALUE,
    NUMBERVALUEFUNC,
    VALUEIDENTIFIER,
    FUNCIDENTIFIER,
    SPECIALFUNCTION,
    GAMESPECIFICDEFINITION,
    ASSIGNMENTOPERATOR,
    LINEEND,
    COMPARISION,
    VALUERETURN,
    ACCESSOPERATOR,
    ADDITIONMODIFY,
    SUBTRACTIONMODIFY,
    ARRAYBRACKETOPEN,
    ARRAYBRACKETEND,
    ARRAYSEPERATOR
}
