package AbstactSyntaxTree;

public enum ASTNodeType {
    ACCESSVALUETYPE,
    DEFINITIONTYPE,
    ANIMATIONFRAMEDEFINITIONTYPE,
    OPERATIONTYPE,
    CALLTYPE,
    CALLSPECIALTYPE,
    CALLGAMESPECTYPE,
    GAMESPECFUNCDEFINITION,
    CONDITIONALTYPE,
    CONDITIONALDETERMINERTYPE,
    CONDITIONALTRUETYPE,
    CONDITIONALFALSETYPE,
    FUNCTIONDEFINITIONTYPE,
    PARAMDEFINITIONTYPE,
    RETURNDEFINITIONTYPE,
    OBJECTDEFINITIONTYPE
}
